### ISSUE TITLE
CMAKE ERROR 

### ISSUE THREAD

**Issue by KennisL** [roboception/rc_genicam_api#10]
Hello ,Happy New Year for the 2019!  
i'm the first time to learn your project. Win10 x64 System, when i using 'cmake'  clicked 'Generate' button . It shows this error:

>   CMake Error at CMakeLists.txt:78 (add_library):
>   Cannot find source file:
> 
> CMake Warning (dev) at CMakeLists.txt:41 (add_definitions):
>   Policy CMP0005 is not set: Preprocessor definition values are now escaped
>   automatically.  Run "cmake --help-policy CMP0005" for policy details.  Use
>   the cmake_policy command to set the policy and suppress this warning.
> This warning is for project developers.  Use -Wno-dev to suppress it.
> 
> CMake Warning (dev) in CMakeLists.txt:
>   No cmake_minimum_required command is present.  A line of code such as
> 
>     cmake_minimum_required(VERSION 3.12)
> 
>   should be added at the top of the file.  The version specified may be lower
>   if you wish to support older CMake versions for this project.  For more
>   information run "cmake --help-policy CMP0000".
> This warning is for project developers.  Use -Wno-dev to suppress it.
> 
> Configuring done
> CMake Error at CMakeLists.txt:78 (add_library):
>   Cannot find source file:
> 
>     F:/coding/KS_GENICAM/KSGENICAM/project_version.cc
> 
>   Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
>   .hpp .hxx .in .txx
> 
> 
> CMake Error at CMakeLists.txt:78 (add_library):
>   No SOURCES given to target: rc_genicam_api_static
> 
I had tried in Win7 system , it is the same problem.  Would you please help me, thanks a lot!

**Comment by heikohimu** [comment]
Are you sure that you set source directory in cmake to the top level directory of rc_genicam_api?

**Comment by KennisL** [comment]
> Are you sure that you set source directory in cmake to the top level directory of rc_genicam_api?

Oh, I set source directory to the directory which named " rc_genicam_api ", but it not the top level directory of rc_genicam_api. It is the subdirectory of the top level directory, Just the same name.   
It works now , Thanks for you help ~
