### ISSUE TITLE
trying to force the IP config fails

### ISSUE THREAD

**Issue by smissan** [roboception/rc_genicam_api#12]
Hi there,

when camera has a permanent IP misconfigured (DHCP is off in the camera), and trying to connect to it to update the IP, device.open() using access mode READONLY or CONROL always fails with error -1005.

The same camera can be accessed with Pleora SDK and correct IP address forced into it.

Is this a Baumer issue or something in the wrapper code?

**Comment by heikohimu** [comment]
You can only open a device, stream data and change parameters if network settings are correct. rc_genicam_api only works for properly configured devices. There are underlying mechanism in the GigE Vision protocol to discover and change network settings even for misconfigured devices. These mechanisms are not (yet) implemented in the rc_genicam_api.

For our rc_visard, there is the rcdiscover tool that can be used to change IP settings temporarily. Thereafter, changes can be made permanent by gc_config. Alternatively, the Baumer SDK (BGAPI) offers a tool called ipconfig to change IP settings. Both ways work even if the network settings of the device are misconfigured.

**Comment by flixr** [comment]
Hi @smissan,

As Heiko mentioned, rc_genicam_api currently doesn't have the capability to set a temporary IP address (FORCE_IP command), as this is _not_ handled by the GenTL layer (Baumer in case of the bundled one).

Could you please clarify what exactly you tried and under which OS?
Also note that when using the Baumer GenTL under Linux you will probably not find the device if it is not reachable (e.g. different subnet), although you will find it with rcdiscover. This is currently still a limitation in the Linux version of the Baumer GenTL.
In any case, to actually open the device it will need to be reachable (e.g. after setting a valid temporary IP).

**Comment by smissan** [comment]
Hi Heiko, Felix,

thank you for your help. We will use rcdiscover approach - we did not realize that GenTL cannot handle/force devices with misconfigured IPs (I since checked the spec). Seems like a big gap in GenTL spec as these situations happen quite often. BTW Baumer .ctl does have functions for forcing the IP, but I guess they are private and definitely not a part of GenTL spec.

thanks again.

**Comment by flixr** [comment]
Ok, closing this issue.
