### ISSUE TITLE
Keine Regel vorhanden ... Linux64_x64/libGCBase_gcc421_v3_0.so

### ISSUE THREAD

**Issue by meuchel** [roboception/rc_genicam_api#15]
For some reason I need to compile version 1.3.12
I follow these steps and get below error when executing make.
Whats wrong or missing?
I use Ubuntu 16.04

cd <main-directory>
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=/usr/local ..
make
make install

ros@xxx:~/xxx/rc_genicam_api/build$ make
Scanning dependencies of target rc_genicam_api
[  2%] Building CXX object rc_genicam_api/CMakeFiles/rc_genicam_api.dir/exception.cc.o
[  5%] Building CXX object rc_genicam_api/CMakeFiles/rc_genicam_api.dir/system.cc.o
[  8%] Building CXX object rc_genicam_api/CMakeFiles/rc_genicam_api.dir/interface.cc.o
[ 11%] Building CXX object rc_genicam_api/CMakeFiles/rc_genicam_api.dir/device.cc.o
[ 14%] Building CXX object rc_genicam_api/CMakeFiles/rc_genicam_api.dir/stream.cc.o
[ 17%] Building CXX object rc_genicam_api/CMakeFiles/rc_genicam_api.dir/cport.cc.o
[ 20%] Building CXX object rc_genicam_api/CMakeFiles/rc_genicam_api.dir/buffer.cc.o
[ 23%] Building CXX object rc_genicam_api/CMakeFiles/rc_genicam_api.dir/config.cc.o
[ 26%] Building CXX object rc_genicam_api/CMakeFiles/rc_genicam_api.dir/image.cc.o
[ 29%] Building CXX object rc_genicam_api/CMakeFiles/rc_genicam_api.dir/imagelist.cc.o
[ 32%] Building CXX object rc_genicam_api/CMakeFiles/rc_genicam_api.dir/project_version.cc.o
[ 35%] Building CXX object rc_genicam_api/CMakeFiles/rc_genicam_api.dir/gentl_wrapper_linux.cc.o
make[2]: *** Keine Regel vorhanden, um das Ziel „../genicam/bin/Linux64_x64/libGCBase_gcc421_v3_0.so“, 
  benötigt von „rc_genicam_api/librc_genicam_api.so.1.3“, zu erstellen.  Schluss.
CMakeFiles/Makefile2:123: die Regel für Ziel „rc_genicam_api/CMakeFiles/rc_genicam_api.dir/all“ scheiterte
make[1]: *** [rc_genicam_api/CMakeFiles/rc_genicam_api.dir/all] Fehler 2
Makefile:160: die Regel für Ziel „all“ scheiterte
make: *** [all] Fehler 2

**Comment by flixr** [comment]
I cannot reproduce this issue. Are you sure you cleaned your build dir?

**Comment by meuchel** [comment]
I did a fresh checkout of this version. That solved the problem.
git clone https://github.com/roboception/rc_genicam_api.git
git checkout 362f505
