### ISSUE TITLE
Read .pfm to numpy and conversion from pixel to world

### ISSUE THREAD

**Issue by zaksel** [roboception/rc_genicam_api#16]
Hi,
i am using a rc_visard 65m and this library to stream disparity images via GenICam.
I read the Image from the .pfm-File (e.g. [image_946691111.740987800_Disparity_1_0.zip](https://github.com/roboception/rc_genicam_api/files/4198321/image_946691111.740987800_Disparity_1_0.zip)) with this snippet (abducted from here: https://lmb.informatik.uni-freiburg.de/resources/datasets/IO.py):
```python
            file = open(path_to_pfm, 'rb')
            #skip metadata
            file.readline().rstrip()
            file.readline().rstrip()
            file.readline().rstrip()
            #read into numpy array Big Endian float
            data = np.fromfile(file, dtype='>f')
            #reshape and flip
            data = np.reshape(data, (480, 640))
            data = np.flipud(data)
```
And get this Image:
![DisparityImage](https://user-images.githubusercontent.com/45262936/74430734-c6a74f00-4e5d-11ea-8d48-3b74f5d7b828.png)

I got the cam parameters via ```gc_info serial_no?Scan3dControl``` and they are:
```python
self.params = {'FocalLengthFactor': 0.843637, 'Scan3dOutputMode': 'DisparityC', 'Scan3dDistanceUnit': 'Pixel', 'Scan3dCoordinateOffset': 0.0, 'Scan3dInvalidDataValue': 0.0, 'Scan3dCoordinateScale': 0.0625, 'Scan3dInvalidDataFlag': 1.0, 'Scan3dFocalLength': 539.927, 'Scan3dBaseline': 0.0649325, 'Scan3dPrincipalPointU': 320.0, 'Scan3dPrincipalPointV': 240.0, 'Baseline': 0.0649325}
```

But when I want to calculate the pixel [240, 320] in real world coordinates like here:  
https://doc.rc-visard.com/latest/en/gigevision.html#image-stream-conversions  
```python
        p_x = (x-self.params['Scan3dPrincipalPointU']) * self.params['Scan3dBaseline']/(dik*self.params['Scan3dCoordinateScale'])
        p_y = (y-self.params['Scan3dPrincipalPointV']) * self.params['Scan3dBaseline']/(dik*self.params['Scan3dCoordinateScale'])
        p_z = self.params['Scan3dFocalLength'] * self.params['Scan3dBaseline']/(dik*self.params['Scan3dCoordinateScale'])
```
The distance for an Object that is `80cm` away is `p_z=7.6m`.  

I think i've made a mistake reading the disparity Image from file, because my Image contains very small values. More like uint8 than uint16. And so `dik` is small and `p_z` is following by that too big.

I have tried to change `dtype='>u2'` when reading the .pfm but then i cant shape the Image to the correct size because i get twice as much values (614400 instead of 307200)?

Anybody knows where I have made a mistake or succeeded with getting the conversion from pixel to world done?

Thanks for your help
derEskimo

**Comment by zaksel** [comment]
**This is interesting, but obviously wrong!**

So when i read the data as 16 bit unsigned Int and after that generate two images from the 614400 Values like below and then reshape and get the pixel value:
```python
data = np.fromfile(file, dtype='>u2')
data1 = data[::2]           #take even indices gives one image
data2 = data[1::2]          #take odd indices gives another
data = np.add(data1, data2) #add them and boom
```
I get `dik=632` and `p_z=887.5mm` which seems way closer.
But i don´t get what happens there and i would really appreciate it if somebody can explain it to me :)

**Comment by flixr** [comment]
The Scan3dCoordinateScale is only needed when converting the 16bit image (as in the GenICam image buffer) to a floating point disparity value in pixels.

Since you are using the cli tool `gc_stream` which already saves the disparity image in float format (*.pfm), you alreay have the floating point value in pixels and the scaling should not be applied again.

**Comment by zaksel** [comment]
Ahh alright. Thank you! So i do the conversion like that:

```python
p_x = (x-self.params['Scan3dPrincipalPointU']) * self.params['Scan3dBaseline']/dik
p_y = (y-self.params['Scan3dPrincipalPointV']) * self.params['Scan3dBaseline']/dik
p_z = self.params['Scan3dFocalLength'] * self.params['Scan3dBaseline']/dik
```
