### ISSUE TITLE
Update to GenApi 3.2.0 Reference Implementation

### ISSUE THREAD

**Issue by r0l1** [roboception/rc_genicam_api#17]
There is a new GenApi reference implementation available.

Great work by the way!

**Comment by flixr** [comment]
Is there anything in particular that you are currently missing and is available in GenApi 3.2.0?

**Comment by r0l1** [comment]
No, currently not. I stumbled over your work as I just started working on an own wrapper for GenApi. I just discovered the version mismatch... Feel free to close this issue if you have no plans on updating...

**Comment by flixr** [comment]
We will definitely update to GenApi 3.2 and GenTL 1.6...
So far there was no pressing need and I was just wondering if there is some particular feature or fix that you are missing.

**Comment by r0l1** [comment]
@flixr thanks for the info. I am fine with that. Works like a charm. Great lib!

**Comment by flixr** [comment]
Updated to latest GenAPI 3.3 with rc_genicam_api v2.5.0
