### ISSUE TITLE
windows compile problems

### ISSUE THREAD

**Issue by tigerxbs59** [roboception/rc_genicam_api#18]
when I compile the project on cmake 3.17.2 , I meet some problems 👍 
CMake Error at CMakeLists.txt:119 (add_library):
  No SOURCES given to target: rc_genicam_api_static

**Comment by heikohimu** [comment]
I cannot reproduce the problem. I tried the same cmake version with the current version of rc_genicam_api and a new build directory. I still have Visual Studio 2017, but it just works. Can you tell me a bit more about your steps to compile?

**Comment by heikohimu** [comment]
No response for one month? I guess the issue is solved.
