### ISSUE TITLE
startStreaming() with non-negative number of buffers does not work

### ISSUE THREAD

**Issue by skaldesh** [roboception/rc_genicam_api#19]
Hi,  
I am executing your example tool `gc_stream` and changed line 495 from:  
`stream[0]->startStreaming();`  
to  
`stream[0]->startStreaming(20);`  

Suddenly, I am only receiving exactly 20 frames, then the program hangs until it fails with the message `Cannot grab images`. I suspect, that buffers are not correctly reused.  
From the documentation of `startStreaming()`:  
```C
/**
      Allocates buffers and registers internal events if necessary and starts
      streaming.

      @param na Number of buffers to acquire. Set <= 0 for infinity.
    */
``` 
I interpreted this as that giving `20` as parameter, it should have allocated 20 buffers and then reuse them, not outputting a maximum of 20 buffers/frames.

**Comment by heikohimu** [comment]
No, there is nothing wrong. With the parameter of the startStreaming() method, you can tell the GigE Vision server to send only a certain number of buffers and then stop sending. With your change in the code, you told the server to send only 20 buffers, but gc_stream does not know about it and runs into a timeout when no more buffers arrive. You would need to close the connection and open it again to get more buffers. That is just the way in which it is specified in the GenICam transport layer (GenTL) specification.

The gc_stream command has already a parameter (e.g. n=20) to receive exactly the specified amount of buffers.

**Comment by heikohimu** [comment]
The confusion is maybe that with this parameter you do not specify the number of buffers (i.e. memory blocks) that are reused, but the total number of buffers that should be sent.

**Comment by skaldesh** [comment]
Ah ok, a little bit unexpected I have to say, but it is clear now, thanks!
