### ISSUE TITLE
Error when running gc_* command

### ISSUE THREAD

**Issue by towardthesea** [roboception/rc_genicam_api#2]
Hi,
I cloned the repository and followed the manual for compilation on the README but when I started trying some `gc_*` command in terminal, I got the same error about `libGCBase_gcc421_v3_0.so`, for example:

> $ gc_info 
> gc_info: error while loading shared libraries: libGCBase_gcc421_v3_0.so: cannot open shared object file: No such file or directory

Please kindly give advice to solve the problem.
Cheers,
Phuong

**Comment by flixr** [comment]
Did you run `make install`?
Where did you install it to? If it's not installed to a standard linux path, you might need to set `LD_LIBRARY_PATH` to find the .so

**Comment by towardthesea** [comment]
Hi,
After having created the issue, I found out the same way as you show to solve it.
Thanks anyway :+1:

**Comment by flixr** [comment]
So did you not run make install at all before?
Or should we document more clearly what happens if you install to non-standard locations?
