### ISSUE TITLE
[Question]: Compatibility with GV-5260CP-M-GL GigE Vision Camera

### ISSUE THREAD

**Issue by dejongyeong** [roboception/rc_genicam_api#25]
Hi, would like to know does this open-source package support the GV-5260CP-M-GL GigE Vision camera [1] in ROS Melodic or ROS Noetic? If do, is there any documentation that listed a list of published topics? Thanks.

[1] https://en.ids-imaging.com/store/gv-5260cp.html

**Comment by flixr** [comment]
This package should work fine with any GigE Vision 2.x compliant camera.
It might be that some of the tools to save images don't support the pixel format used...

But this is not a ROS package! It is just a convenience wrapper for GenICam/GigE vision...

**Comment by dejongyeong** [comment]
Thanks @flixr for the information.
