### ISSUE TITLE
Where can I find examples of using this API?

### ISSUE THREAD

**Issue by Bart-van-Ingen** [roboception/rc_genicam_api#30]
I have found the following sources:

[http://docs.ros.org/en/noetic/api/rc_genicam_api/html/annotated.html](http://docs.ros.org/en/noetic/api/rc_genicam_api/html/annotated.html)
[https://doc.rc-visard.com/latest/en/gigevision.html#sect-genicam](https://doc.rc-visard.com/latest/en/gigevision.html#sect-genicam )

however none of them give me a simple example of using this library.

Where would i be able to find some ?

**Comment by flixr** [comment]
We currently don't have any dedicated examples, but the [tools](https://github.com/roboception/rc_genicam_api/tree/master/tools) essentially serve as examples.
