### ISSUE TITLE
Issue with using READONLY mode for Basler camera

### ISSUE THREAD

**Issue by shahromil16** [roboception/rc_genicam_api#31]
I am using a Basler acA1280-60gc and using the .cti files provided by Basler to use it with GenICam C++ API. 

**What I am trying to do:**
Run the device in 2 modes (`CONTROL` and `READONLY`) and get streams simultaneously from them. Or if there is a better way than this to get 2+ streams simultaneously from a single camera. 

**Problem:**
I am able to grab frames using the device in `CONTROL` mode. However, I when changing to `READONLY` mode, I am able to start the device in that mode but not able to stream data into a buffer. I am trying to follow the documentation and the code as per the examples in `tools`.

While running the camera in `CONTROL` mode and trying to run another piece in `READONLY` mode, the `CONTROL` mode runs fine but for `READONLY` mode, I am receiving the following error:
```
terminate called after throwing an instance of ‘rcg::GenTLException’
   what():   Stream::startStreaming():   Unknown error (-1017)
```

I am attaching the results of `$ ./gc_info -l`:
```
Transport Layer ProducerGEV.cti
Vendor:         Basler
Model:          GEV
Vendor version: 1.0.0.0
TL type:        GEV
Name:           ProducerGEV-1.4.0.cti
Pathname:       /opt/pylon/lib/gentlproducer/gtl/ProducerGEV-1.4.0.cti
Display name:   Basler GEV GenTL Producer
GenTL version   1.5

    Interface     Basler GEV GenTL Interface Module
    Display name: GigE Vision
    TL type:      GEV

        Device             Basler acA1280-60gc (23741763)
        Vendor:            Basler
        Model:             acA1280-60gc
        TL type:           GEV
        Display name:      gige
        User defined name: gige
        Access status:     Unknown
        Serial number:     23741763
        Version:           106487-18
        TS Frequency:      0

Transport Layer ProducerU3V.cti
Vendor:         Basler
Model:          U3V
Vendor version: 1.0.0.0
TL type:        U3V
Name:           ProducerU3V.cti
Pathname:       /opt/pylon/lib/gentlproducer/gtl/ProducerU3V.cti
Display name:   Basler U3V GenTL Producer
GenTL version   1.5

    Interface     Basler U3V GenTL Interface Module
    Display name: USB3 Vision
    TL type:      U3V
```

I am attaching the results of `$ ./gc_config -l`:
```
ID:                         Basler GEV GenTL Interface Module:23741763
GenTL ID:                   Basler acA1280-60gc (23741763)
Serial number:              23741763
User defined ID:            gige

Interface 0:
  MAC Address:              3053391843

  Current IP:               c0a80165
  Current subnet mask:      ffffff00
  Current gateway:          c0a80101

  Persistent IP on/off:     
    Persistent IP:          0
    Persistent subnet mask: 0
    Persistent gateway:     0
  DHCP on/off:              
  Link local on/off:        

Ptp parameters are not available
```

Any help in this is appreciated. All I want is to access the camera simultaneously by multiple client nodes.

**Comment by flixr** [comment]
I don't think this is possible (at least not in a straightforward way) with GenICam/GigE Vision.
Only applications registered with EXCLUSIVE or CONTROL access can write to a device (this includes opening a stream channel to receive images).
AFAIK your only bet might be to use multicasting for the stream channel to send the data to multiple locations.
But even then only the application with write access (CONTROL) can set up the stream channel with a multicast group target IP.
In most cases this is not really what you would want or can easily have under control.

Also the GenTL access mode READONLY is not present in GEV, so I guess this gets mapped to the GEV mode MONITOR access (which devices are not required to support).

**Comment by shahromil16** [comment]
As a first, the Basler camera I am using supports ‘MONITOR’ mode. Using the Pylon SDK, I am able to run multiple streams from a single camera. I want to replicate that with GenICam. 

Secondly, for multicast mode, is there a way to do that using GenICam? I could not find anything in the SDK that suggests so.

**Comment by flixr** [comment]
When you said `GenICam` here I guess you actually meant this wrapper `rc_genicam_api`?

AFAIK to use "multicast mode" you only need to set a multicast address as destination address.

I don't know how Pylon handles this, would be interesting to know.
In any case I don't think you can call `startStreaming` (or at least create a new stream channel) from your secondary application with monitor access.
At least this is how I currently understand the GigE Vision Standard.

**Comment by shahromil16** [comment]
@flixr 
Yes. I am referring to `rc_genicam_api` when I wrote `GenICam`.
> When you said GenICam here I guess you actually meant this wrapper rc_genicam_api?

Is there a specific way to do it using `rc_genicam_api`? Couldn't find any examples of that.
> AFAIK to use "multicast mode" you only need to set a multicast address as destination address.

Correct. Whilst debugging I realized that calling while in `READONLY` mode, the `startStreaming` causes the issue which means the stream data is not offloaded to the `rcg::Buffer` class `buffer`. 
> In any case I don't think you can call startStreaming (or at least create a new stream channel) from your secondary application with monitor access.

However for Pylon SDK this is not the case. I can call 1 stream with `CONTROL` mode and can call multiple other streams using `MONITOR` mode without issues. 

Any help with setting up "multicast mode" using `rc_genicam_api` would be helpful.

**Comment by flixr** [comment]
Hm... actually not sure how to set a multicast destination IP address using `rc_genicam_api`...
@heikohimu any thoughts?

But the the GigE Vision standard clearly states that only the the primary application is allowed to configure stream channels...
Not sure how Pylon works around that then...

**Comment by heikohimu** [comment]
My first thought is that this does not work, but since it seems to work in Pylon, there must be a way. I am just not sure if this is an extension or if it possible within the GenICam standard.

The error in Stream::startStreaming() is either because allocation or queuing of buffers failed, registering the event failed or calling start acquisition on the GenTL data stream object failed. In the exception, I am reporting the last error. It is unfortunate that the producer reports an unknown error. We would need to find out the location where err=true is set in that method. Then, we may know a little bit more. Unfortunately, I do not have any time at the moment.

**Comment by shahromil16** [comment]
@heikohimu 
Thanks for looking into this. 
I will try to debug and identify where exactly in `Stream::startStreaming()` the error happens and will report here.
