### ISSUE TITLE
Does it support in nvidia TX2 ARM(V8) product

### ISSUE THREAD

**Issue by ericzhuo-cpu** [roboception/rc_genicam_api#33]
Hi,
I just used the library to capture cammer picture in NVIDIA  TX2 borad.
And the picture size is 2469888. 
It failed to get the correct data when try to get the 200nd picture every time.
However, it run well in windows and VMWARE virtural environment.
Could you show your suggestion?

Thanks

**Comment by heikohimu** [comment]
The TX2 board is not in our focus, but it should work. I recently used the rc_genicam_api on a Xavier AGX board with USB cameras. What camera do you use (model, manufacturer)?

**Comment by ericzhuo-cpu** [comment]
Thanks for your reply.
The camera is manufacture. We used another library called libarena.so to replace it.
And it could work now. 
Not sure why. 


















At 2022-01-03 15:17:31, "Heiko Hirschmüller" ***@***.***> wrote:

The TX2 board is not in our focus, but it should work. I recently used the rc_genicam_api on a Xavier AGX board with USB cameras. What camera do you use (model, manufacturer)?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
