### ISSUE TITLE
saving values instead of images

### ISSUE THREAD

**Issue by denizsoysal** [roboception/rc_genicam_api#41]
Hello,
Is there a way to save disparity values instead of the image ? I guess there is some loss of information when doing the color mapping and I want to avoid that.

Thanks !

**Comment by flixr** [comment]
I don't quite understand what you mean. There is no color mapping done for a disparity image.

**Comment by flixr** [comment]
Closing this, as I don't see any issue here.
Feel free to re-open and clarify if needed.
