### ISSUE TITLE
[BUG] Get this error ```Interface::open(): Module not initialized (-1002)``` occasionally

### ISSUE THREAD

**Issue by MyronRodrigues-StreetDrone** [roboception/rc_genicam_api#43]
I get the following error and the system wont recover unless rebooted.

OS: Ubuntu 22.04
Cameras: Basler. FLIR
On calling: `rcg::getDevices()`

```bash
terminate called after throwing an instance of 'rcg::GenTLException'
  what():  Interface::open(): Module not initialized (-1002)
Aborted (core dumped)
```

from my reading ive found this [document](https://www.emva.org/wp-content/uploads/GenICam_GenTL_1_5.pdf), check page 56

**Comment by flixr** [comment]
Can you please provide some more details?
Which GenTL provider are you using? You can see that with `gc_info -l`.

**Comment by MyronRodrigues-StreetDrone** [comment]
For sure. Here's what I got. Its the one that comes with the rc_genicam_api I guess. Also is it possible to change it? If yes may I know how.

```
Transport Layer /usr/lib/x86_64-linux-gnu/rc_genicam_api/libbgapi2_gige.cti_2.9.22968.22969
Vendor:         Baumer
Model:          bgapi2_gige
Vendor version: 2.9.22968.22969
TL type:        GEV
Name:           libbgapi2_gige.cti
Pathname:       /usr/lib/x86_64-linux-gnu/rc_genicam_api/libbgapi2_gige.cti
Display name:   Baumer GEV TL
GenTL version   1.5
```

**Comment by flixr** [comment]
Sure, you can set the path to the TL: https://github.com/roboception/rc_genicam_api#finding-the-transport-layer
