### ISSUE TITLE
Transport Layer 

### ISSUE THREAD

**Issue by NiklasEiler** [roboception/rc_genicam_api#47]
I installed the rc_genicam_api in my Ubuntu home directory. When I run the gc_info -l the console prints out that the transport layer is missing like in the section about the transport layer. The problem for me is now how I change the path ( which command) and to what(I don’t know where the transport layer is).
PS:i am new to Linux und your api

**Comment by flixr** [comment]
How did you compile/install rc_genicam_api?
Did you follow https://github.com/roboception/rc_genicam_api#linux?
If not you can try to set `GENICAM_GENTL64_PATH` to the directly where the cti files are, e.g.
```
export GENICAM_GENTL64_PATH=~/rc_genicam_api/tree/master/baumer/Ubuntu-16.04/arm64
gc_config -l
```
You can also build a debian package and install that or install the prebuilt one which you can download from https://github.com/roboception/rc_genicam_api/releases
