### ISSUE TITLE
gc_stream Exception: Stream::open(): Write max packet size failed with 0x8002

### ISSUE THREAD

**Issue by meuchel** [roboception/rc_genicam_api#6]
I get 

$ gc_stream eno1:00_0c_d4_12_32_2b
Exception: Stream::open(): Write max packet size failed with 0x8002
 
with this UV camera
Vendor: JAI Ltd., Japan
Model:  BM-141GE

Regarding the message I found this in
http://www.emva.org/wp-content/uploads/GenCP_1.1.pdf
0x8002
GENCP_INVALID_PARAMETER
At least one command parameter 
of CCD or SCD is invalid or out of range.

What does this mean?

**Comment by flixr** [comment]
The error code 0x8002 indeed means that a parameter was invalid (although not from GenCP).

Does `gc_info` work? What do you get for the packet size there?

**Comment by meuchel** [comment]
gc_info works.
GevSCPSPacketSize is 8164
Networkcard has MTU 8194
Also I must mention opening Mono8 stream works with gc_stream but not with Mono12 (2 bpp).
Unfortunately I need working Mono12.

**Comment by flixr** [comment]
Mono12 conversion is currently not implemented in gc_stream, see https://github.com/roboception/rc_genicam_api/blob/e6aac2b017dd67454bd9230535c3a58c83155d36/tools/gc_stream.cc#L84
You could add that and make a pull request...
But this should be unrelated to the problem with packet size you reported.

**Comment by meuchel** [comment]
At the end I don't want to use gc_stream tool to grab images. I'm using this lib to create a ROS node.
I opened the ticket against gc_stream because it has exactly the same problem when opening the stream. When having a look into the lib there seems to be nothing special to open a stream.
https://github.com/roboception/rc_genicam_api/blob/f7f1621fc3ac5d638292e3d5d1ea9393959ecd9d/rc_genicam_api/stream.cc#L92
Now is the question what to do to get it to work?
When I use e.g. ebus player or Aravis library it woks out of the box. (I don't want to use Aravis because I have other issues with it. Thats the reason why I try your lib).

**Comment by heikohimu** [comment]
Can you test the Baumer SDK with your camera, i.e. bexplorer viewer, see https://www.baumer.com/us/en/product-overview/image-processing-identification/software/baumer-gapi-sdk/c/14174

If this works, we can look for an error in rc_genicam_api. If it does not, then we can ask Baumer or use you could use another GenTL library together with rc_genicam_api.

**Comment by flixr** [comment]
I think there are two different issues here:
1. stream open doesn't work on your device
2. the gc_stream example tool doesn't support mono12

But I'm confused about the stream open problem, since you said that it worked with mono8. But that was with a different camera, right?

**Comment by meuchel** [comment]
It is the same camera as in the first post. 

When configured with PixelFormat Mono8 "stream start" works and gc_stream stores an image.
When configured Mono12 "stream start" fails with the exception.
So we just talk about the bug in gc_stream that it cant start the stream with Mono12 (to store an image does not care to me in the moment).

Later I will try Baumer SDK as suggested by Heiko. But in the moment I have no acces to the camera and this may take some days in order to be able to do that test.

**Comment by flixr** [comment]
@meuchel any updates here?

**Comment by meuchel** [comment]
sorry, I have no more access to this camera. So cant test with it. I think you can close this ticket.
