### ISSUE TITLE
Linker Error

### ISSUE THREAD

**Issue by navona** [roboception/rc_genicam_api#7]
I would like to use the roboception image data in my own C++ program. I have downloaded the binaries (rc_genicam_api, v1.3.6 for Win64).
When I try to compile a program which is quite similar to your example gc_pointcloud.cc. I am getting a linker error:
LINK : fatal error LNK1104: Cannot open file "GCBase_MDd__v3_0.lib"

I am using visual studio 2015 (v140) compiler. I added the additional library directory (path to rc_genicam_api-win64-vc14-v1.3.6\lib) to the linker properties and added as additional dependencies GCBase_MD_VC120_v3_0.lib;GenApi_MD_VC120_v3_0.lib;rc_genicam_api.lib.

Where is my fault? Thanks in advance.

**Comment by heikohimu** [comment]
I am not an expert regarding Windows and Visual Studio, but I think that MDd instead of MD means that the linker is looking for a debug version of the library, which is not available. I do not know how to tell Visual Studio to use the non-debug libraries instead. Can you try compiling your code as release instead?

**Comment by navona** [comment]
I allready tried this. Then the error says:
LINK : fatal error LNK1104: Cannot open file "GCBase_MD__v3_0.lib"

**Comment by heikohimu** [comment]
I think it might be due to some pragmas in the GenICam reference implementation that try automatic linking. Can you try defining the symbol GENICAM_NO_AUTO_IMPLIB in your project with "/DGENICAM_NO_AUTO_IMPLIB"?

**Comment by navona** [comment]
I added the line as suggested:
#define GENICAM_NO_AUTO_IMPLIB "/DGENICAM_NO_AUTO_IMPLIB"

This solved the problem. Thank you!!

**Comment by heikohimu** [comment]
Good!

#define GENICAM_NO_AUTO_IMPLIB without anything afterwards would have been enough. Or, better set "/DGENICAM_NO_AUTO_IMPLIB" in your project file so that it is defined for all your modules.
