### ISSUE TITLE
gc_stream Exception: Node is not writable. : AccessException thrown in node 'AcquisitionStart' while calling 'AcquisitionStart.Execute()' (file 'CommandT.h', line 61)

### ISSUE THREAD

**Issue by dmccskylove** [roboception/rc_genicam_api#9]
gc_stream 2F01F38YAK00044
Exception: Node is not writable. : AccessException thrown in node 'AcquisitionStart' while calling 'AcquisitionStart.Execute()' (file 'CommandT.h', line 61)

When I use baumer Camera Explorer,it`s look like work.
![image](https://user-images.githubusercontent.com/6083168/49798903-6d85ec00-fd7e-11e8-8b9d-b72e093a9c94.png)

unbutu16.04 x64
device info got from gc_info
TL type:      GEV

        Device         devicemodul3c_ef_8c_94_ba_a4
        Vendor:        Machine Vision
        Model:         A5501MG20
        TL type:       GEV
        Display name:  Camera0
        Access status: ReadWrite
        Serial number: 2F01F38YAK00044
        Version:       
        TS Frequency:  0

**Comment by heikohimu** [comment]
First of all, we are offering this package for supporting our own camera, although we try to keep it as general as possible. So, I can try to help ...

Can you post the output of "gc_info 2F01F38YAK00044"?

**Comment by dmccskylove** [comment]
gc_info enp2s0f0:2F01F38YAK00044 
Device:        devicemodul3c_ef_8c_94_ba_a4
Vendor:        Machine Vision
Model:         A5501MG20
TL type:       GEV
Display name:  Camera0
User name:     
Serial number: 2F01F38YAK00044
Version:       
TS Frequency:  0

Available streams:
  Stream ID: Stream0

Available features:
  Category: Root (RO)
    Category: DeviceControl (RO)
      Enumeration: DeviceType (RO) [Transmitter Receiver Transceiver Peripheral]: Transmitter
      Enumeration: DeviceScanType (RW) [Areascan]: Areascan
      String: DeviceVendorName (RO): Machine Vision
      String: DeviceModelName (RO): A5501MG20
      String: DeviceManufacturerInfo (RO): Machine Vision
      String: DeviceVersion (RO): V1.000.00.0.R(20170719,30273)
      String: DeviceFirmwareVersion (RO): 20170718,211828,00800000,2
      String: DeviceSerialNumber (RO): 2F01F38YAK00044
      String: DeviceUserID (RW): Camera0
      Enumeration: DeviceTLType (RW) [GigEVision]: GigEVision
      Integer: DeviceTLVersionMajor (RO) [0, 65535]: 2 
      Integer: DeviceTLVersionMinor (RO) [0, 65535]: 0 
      Float: DeviceMaxThroughput (RO) [-3.40282e+38, 3.40282e+38]: 1000 Mbps
      Enumeration: DeviceCharacterSet (RO) [UTF8 ASCII]: UTF8
      Command: DeviceReset (WO)
      Enumeration: DeviceTemperatureSelector (RW) [Sensor Mainboard]: Sensor
      Float: DeviceTemperature (RO) [-3.40282e+38, 3.40282e+38]: 40.75 C
      Boolean: DeviceRegistersIsBigEndian (RO): 1
      Enumeration: DeviceTLVersionSelector (RW) [Version_1_0 Version_2_0]: Version_2_0
    Category: ImageFormatControl (RO)
      Enumeration: Binning (RW) [Off X Y XY]: Off
      Enumeration: Decimation (RW) [Off X Y XY]: Off
      Integer: SensorWidth (RO) [0, 4294967295]: 2592 
      Integer: SensorHeight (RO) [0, 4294967295]: 2048 
      Integer: WidthMax (RO) [0, 4294967295]: 2592 
      Integer: HeightMax (RO) [0, 4294967295]: 2048 
      Integer: Width (RW) [64, 2592]: 2592 
      Integer: Height (RW) [32, 2048]: 2048 
      Integer: OffsetX (RW) [0, 0]: 0 
      Integer: OffsetY (RW) [0, 0]: 0 
      Boolean: ReverseX (RW): 0
      Boolean: ReverseY (RW): 0
      Enumeration: PixelFormat (RW) [Mono8 Mono10 Mono10Packed]: Mono8
      Enumeration: PixelSize (RO) [Bpp1 Bpp2 Bpp4 Bpp8 Bpp10 Bpp12 Bpp14 Bpp16 Bpp24 Bpp30 Bpp32 Bpp36 Bpp48 Bpp64]: Bpp8
      Enumeration: ImageCompressionMode (NI) 
      Integer: ImageCompressionQuality (NI) 
      Enumeration: PixelColorFilter (RO) [None BayerRG BayerGB BayerGR BayerBG]: None
      Integer: PixelDynamicRangeMin (RO) [0, 4294967295]: 0 
      Integer: PixelDynamicRangeMax (RO) [0, 4294967295]: 255 
      Enumeration: TestImageSelector (RW) [Off TestImage1 TestImage2]: Off
    Category: AcquisitionControl (RO)
      Enumeration: AcquisitionMode (RW) [Continuous SingleFrame MultiFrame]: Continuous
      Command: AcquisitionStart (NA)
      Command: AcquisitionStop (NA)
      Integer: AcquisitionFrameCount (RW) [1, 255]: 1 
      Float: AcquisitionFrameRate (RW) [1, 2000]: 20 Hz
      Boolean: AcquisitionFrameRateEnable (RW): 0
      Enumeration: AcquisitionStatusSelector (RW) [AcquisitionTriggerWait FrameTriggerWait]: FrameTriggerWait
      Boolean: AcquisitionStatus (RO): 0
      Enumeration: TriggerSelector (RW) [AcquisitionStart FrameStart]: FrameStart
      Enumeration: TriggerMode (RW) [Off On]: Off
      Enumeration: TriggerSource (RW) [Software Line1]: Software
      Command: TriggerSoftware (WO)
      Boolean: TriggerSoftwareSpeedUp (RW): 1
      Enumeration: TriggerActivation (NA) 
      Float: TriggerDelay (RW) [0, 1e+06]: 0 us
      Integer: TriggerMultiplier (RW) [10, 65535]: 50 
      Integer: TriggerCounter (RW) [-9223372036854775808, 9223372036854775807]: 1 
      Float: LightTriggerDelay (RW) [0, 1e+06]: 0 us
      Enumeration: ExposureMode (RW) [Timed]: Timed
      Integer: ExposureTargetBrightness (RW) [0, 100]: 50 
      Enumeration: ExposureAuto (RW) [Off Once Continuous]: Off
      Float: ExposureTime (RW) [1, 1e+06]: 5000 us
      Float: ResultingFrameRateAbs (RO) [0, 1e+06]: 20.0228 Hz
    Category: DigitalIOControl (RO)
      Enumeration: LineSelector (RW) [Line0 Line1]: Line0
      Enumeration: LineMode (RW) [Output]: Output
      Boolean: LineInverter (RW): 0
      Boolean: LineStatus (RO): 0
      Integer: LineStatusAll (RO) [0x0, 0xffffffff]: 0x0 
      Enumeration: LineSource (RW) [ExposureActive FrameTriggerWait Timer0Active AcquisitionTriggerWait UserOutput0 LightTrigger]: ExposureActive
      Enumeration: LineFormat (RO) [OptoCoupled TTL]: OptoCoupled
      Float: LineDebouncerTimeAbs (NA) 
      Enumeration: UserOutputSelector (RW) [UserOutput0]: UserOutput0
      Boolean: UserOutputValue (RW): 0
      Integer: UserOutputValueAll (RW) [0, 4294967295]: 0 
    Category: EventControl (RO)
      Enumeration: EventSelector (RW) [ExposureEnd FrameTrigger FrameStart AcquisitionStart AcquisitionTrigger ReadOut]: ExposureEnd
      Enumeration: EventNotification (RW) [Off On]: Off
      Enumeration: ExposureEndEn (RW) [Off On]: Off
      Enumeration: FrameTriggerEn (RW) [Off On]: Off
      Enumeration: FrameStartEn (RW) [Off On]: Off
      Enumeration: AcquisitionStartEn (RW) [Off On]: Off
      Enumeration: AcquisitionTriggerEn (RW) [Off On]: Off
    Category: LUTControl (RO)
      Enumeration: LUTSelector (RW) [Luminance]: Luminance
      Boolean: LUTEnable (RW): 0
      Integer: LUTIndex (RW) [0, 4095]: 0 
      Integer: LUTValue (RO) [0, 4095]: 0 
      Register: LUTValueAll (RW)
    Category: AnalogControl (RO)
      Enumeration: GainSelector (RW) [All]: All
      Enumeration: GainAuto (NI) 
      Float: Gain (RW) [1, 6]: 1 
      Float: GainRaw (RW) [1, 6]: 1 
      Enumeration: BlackLevelAuto (RW) [Off Once Continuous]: Continuous
      Enumeration: BlackLevelSelector (RW) [All]: All
      Integer: BlackLevel (RO) [0, 255]: 20 
      Integer: BlackLevelRaw (RO) [0, 255]: 20 
      Enumeration: BalanceWhiteAuto (NI) 
      Enumeration: BalanceRatioSelector (NI) 
      Float: BalanceRatio (NI) 
      Float: Gamma (RW) [0, 3.99998]: 1 
    Category: TransportLayerControl (RO)
      Category: GigEVision (RO)
        Integer: GevVersionMajor (RO) [0, 65535]: 2 
        Integer: GevVersionMinor (RO) [0, 65535]: 0 
        Boolean: GevDeviceModeIsBigEndian (RO): 1
        Enumeration: GevDeviceClass (RO) [Transmitter Receiver Transceiver Peripheral]: Transmitter
        Enumeration: GevDeviceModeCharacterSet (RO) [UTF8 ASCII]: UTF8
        Enumeration: GevPhysicalLinkConfiguration (RW) [SingleLink]: SingleLink
        Enumeration: GevCurrentPhysicalLinkConfiguration (RO) [SingleLink MultiLink StaticLAG DynamicLAG]: SingleLink
        Boolean: GevPAUSEFrameReception (RW): 1
        Boolean: GevPAUSEFrameTransmission (RW): 1
        Boolean: GevIEEE1588 (NI)
        Enumeration: GevIEEE1588ClockAccuracy (NI) 
        Enumeration: GevIEEE1588Status (NI) 
        Boolean: GevSCCFGUnconditionalStreaming (NI)
        Boolean: GevSCCFGExtendedChunkData (NI)
        Enumeration: GevSCPDirection (RO) [Transmitter Receiver]: Transmitter
        Boolean: GevSCPSBigEndian (RW): 0
      Integer: PayloadSize (RO) [0, 4294967295]: 5308416 
      Integer: GevActiveLinkCount (RO) [0, 15]: 1 
      Integer: GevInterfaceSelector (RW) [0, 0]: 0 
      Integer: GevLinkSpeed (RO) [0, 4294967295]: 1000 
      Integer: GevMACAddress (RO) [0x8000000000000000, 0x7fffffffffffffff]: 0x3cef8c94baa4 
      Enumeration: GevSupportedOptionSelector (RW) [SingleLink MultiLink StaticLAG DynamicLAG PAUSEFrameReception PAUSEFrameGeneration IPConfigurationLLA IPConfigurationDHCP IPConfigurationPersistentIP StreamChannelSourceSocket StandardIDMode MessageChannelSourceSocket CommandsConcatenation WriteMem PacketResend Event EventData PendingAck IEEE1588 Action UnconditionalAction ScheduledAction PrimaryApplicationSwitchover ExtendedStatusCodes ExtendedStatusCodesVersion2_0 DiscoveryAckDelay DiscoveryAckDelayWritable TestData ManifestTable CCPApplicationSocket LinkSpeed HeartbeatDisable SerialNumber UserDefinedName StreamChannel0BigAndLittleEndian StreamChannel0MultiZone StreamChannel0PacketResendDestination StreamChannel0AllInTransmission StreamChannel0UnconditionalStreaming StreamChannel0ExtendedChunkData]: SingleLink
      Boolean: GevSupportedOption (RO): 1
      Boolean: GevCurrentIPConfigurationLLA (RO): 1
      Boolean: GevCurrentIPConfigurationDHCP (RW): 0
      Boolean: GevCurrentIPConfigurationPersistentIP (RW): 1
      Integer: GevCurrentIPAddress (RO) [0x0, 0xffffffff]: 0xc0a80205 
      Integer: GevCurrentSubnetMask (RO) [0x0, 0xffffffff]: 0xffffff00 
      Integer: GevCurrentDefaultGateway (RO) [0x0, 0xffffffff]: 0x0 
      Enumeration: GevIPConfigurationStatus (RO) [None PersistentIP DHCP LLA ForceIP]: PersistentIP
      String: GevFirstURL (RO): Local:A5501MG20.zip;f0000000;9ca0
      String: GevSecondURL (RO): 
      Integer: GevNumberOfInterfaces (RO) [0, 4294967295]: 1 
      Integer: GevPersistentIPAddress (RW) [0x0, 0xffffffff]: 0xc0a80205 
      Integer: GevPersistentSubnetMask (RW) [0x0, 0xffffffff]: 0xffffff00 
      Integer: GevPersistentDefaultGateway (RW) [0x0, 0xffffffff]: 0x0 
      Integer: GevMessageChannelCount (RO) [0, 1]: 1 
      Integer: GevStreamChannelCount (RO) [0, 512]: 1 
      Integer: GevHeartbeatTimeout (RW) [500, 4294967295]: 3000 
      Integer: GevTimestampTickFrequency (RO) [-9223372036854775808, 9223372036854775807]: 125000000 
      Command: GevTimestampControlLatch (WO)
      Command: GevTimestampControlReset (WO)
      Integer: GevTimestampValue (RO) [-9223372036854775808, 9223372036854775807]: 0 
      Enumeration: GevGVCPExtendedStatusCodesSelector (RW) [Version1_1 Version2_0]: Version1_1
      Boolean: GevGVCPExtendedStatusCodes (RW): 0
      Boolean: GevGVCPPendingAck (RW): 1
      Boolean: GevGVCPHeartbeatDisable (RW): 0
      Integer: GevGVCPPendingTimeout (RO) [0, 4294967295]: 200 
      Enumeration: GevGVSPExtendedIDMode (RW) [Off On]: Off
      Enumeration: GevCCP (RW) [ExclusiveAccess ControlAccess]: 
      Integer: GevPrimaryApplicationSocket (RO) [0, 65535]: 0 
      Integer: GevPrimaryApplicationIPAddress (RO) [0x0, 0xffffffff]: 0x0 
      Integer: GevMCPHostPort (RW) [0, 65535]: 0 
      Integer: GevMCDA (RW) [0x0, 0xffffffff]: 0x0 
      Integer: GevMCTT (RW) [0, 4294967295]: 300 
      Integer: GevMCRC (RW) [0, 4294967295]: 2 
      Integer: GevMCSP (RO) [0, 65535]: 0 
      Integer: GevStreamChannelSelector (RW) [0, 0]: 0 
      Integer: GevSCPInterfaceIndex (RW) [0, 0]: 0 
      Integer: GevSCPHostPort (RW) [0, 65535]: 0 
      Boolean: GevSCPSFireTestPacket (RW): 0
      Boolean: GevSCPSDoNotFragment (RW): 1
      Integer: GevSCPSPacketSize (RW) [300, 16266]: 1500 
      Enumeration: GevSCPDSwitch (RW) [On Off]: Off
      Integer: GevSCPD (RW) [0, 4294967295]: 0 
      Integer: GevSCDA (RW) [0x0, 0xffffffff]: 0x0 
      Integer: GevSCSP (RO) [0, 65535]: 20202 
    Category: UserSetControl (RO)
      Enumeration: UserSetSelector (RW) [Default UserSet1 UserSet2]: UserSet1
      Command: UserSetLoad (RW)
      Command: UserSetSave (RW)
      Enumeration: UserSetDefault (RW) [Default UserSet1]: UserSet1
      Enumeration: UserSetLoadLastUserSet (RO) [Default UserSet1 UserSet2]: UserSet1
      Enumeration: UserSetLoadStatus (RO) [InProgress Failure Success]: Success
    Category: ChunkDataControl (RO)
      Boolean: ChunkModeActive (NA)
      Enumeration: ChunkSelector (NA) 
      Boolean: ChunkEnable (NA)
      Integer: ChunkCounter0Value (NA) 
      Integer: ChunkCounter1Value (NA) 
    Category: ColorTransformationControl (RO)
      Category: ColorTransformationControlInvisible (RO)
        Boolean: ColorTransformationRgbToRgbEnable (RW): 1
        Boolean: ColorTransformationRgbToYuvEnable (RW): 1
        Register: ColorTransformationValueRaw (RW)
      Enumeration: ColorTransformationSelector (NI) 
      Boolean: ColorTransformationEnable (NI)
      Enumeration: ColorTransformationValueSelector (NI) 
      Float: ColorTransformationValue (NI) 
    Category: CounterAndTimerControl (RO)
      Enumeration: CounterSelector (RW) [Counter0 Counter1]: Counter0
      Enumeration: CounterResetSource (RW) [Off SoftwareSignal0 Line1]: Off
      Enumeration: CounterEventSource (RO) [FrameTrigger FrameStart]: FrameTrigger
      Command: CounterReset (NA)
      Enumeration: TimerSelector (RW) [Timer0]: Timer0
      Enumeration: TimerTriggerSource (RW) [ExposureStart]: ExposureStart
      Enumeration: TimerTriggerActivation (RW) [RisingEdge FallingEdge AnyEdge]: RisingEdge
      Integer: TimerDelay (RW) [1, 65535]: 1024 
      Integer: TimerDuration (RW) [1, 65535]: 4096 
    Category: TimerControl (RO)
      Category: TimerControlInvisible (RO)
        Integer: Timer0DelayRawVal (RW) [0, 4294967295]: 1024 
        Enumeration: Timer0TriggerSourceVal (RW) [NewEntry0]: NewEntry0
        Integer: Timer0DurationRawVal (RW) [0, 4294967295]: 4096 
        Enumeration: Timer0TriggerActivationVal (RW) [NewEntry0 NewEntry1 NewEntry2]: NewEntry0
    Category: ISPControl (RO)
      Enumeration: SharpnessEnabled (RW) [Off On]: Off
      Integer: Sharpness (NA) 
      Integer: Hue (NI) 
      Integer: Saturation (NI) 
      Enumeration: DenoisingEnabled (RW) [Off On]: Off
      Integer: Denoising (NA) 
      Integer: DigitalShift (RW) [0, 4]: 0 
      Integer: Brightness (RW) [0, 100]: 50 
      Integer: Contrast (RW) [0, 100]: 50 
      Enumeration: ContrastMode (RW) [Off Once Continue]: Off
      Integer: ContrastThreshold (RW) [0, 255]: 128 
      Boolean: FPNCalibrationStatus (RO): 0
      Command: FPNPerformCalibration (RW)
      Enumeration: FFCEnable (NI) 
      Enumeration: IRISMode (NI) 
    Category: TLParamsLockedCategory (RO)
      Integer: TLParamsLocked (RW) [0, 1]: 0

**Comment by dmccskylove** [comment]
and this is info I run baunmer\sdk_example\c++\build_linux_debug\0_Common\001_ImageCaptureMode_Polling\001_ImageCaptureMode_Polling.

###############################################################
# PROGRAMMER'S GUIDE Example 001_ImageCaptureMode_Polling.cpp #
###############################################################


SYSTEM LIST
###########

5.1.2   Detected systems:  2
  5.2.1   System Name:     libbgapi2_gige.cti
          System Type:     GEV
          System Version:  2.9.18805.18905
          System PathName: /usr/local/lib/baumer/libbgapi2_gige.cti

  5.2.1   System Name:     libbgapi2_usb.cti
          System Type:     U3V
          System Version:  2.9.18666.18905
          System PathName: /usr/local/lib/baumer/libbgapi2_usb.cti

SYSTEM
######

5.1.3   Open next system 
  5.2.1   System Name:     libbgapi2_gige.cti
          System Type:     GEV
          System Version:  2.9.18805.18905
          System PathName: /usr/local/lib/baumer/libbgapi2_gige.cti

        Opened system - NodeList Information 
          GenTL Version:   1.5

INTERFACE LIST
##############

5.1.4   Detected interfaces: 4
  5.2.2   Interface ID:      docker0
          Interface Type:    GEV
          Interface Name:    docker0

  5.2.2   Interface ID:      enp2s0f0
          Interface Type:    GEV
          Interface Name:    enp2s0f0

  5.2.2   Interface ID:      enp2s0f1
          Interface Type:    GEV
          Interface Name:    enp2s0f1

  5.2.2   Interface ID:      enp3s0
          Interface Type:    GEV
          Interface Name:    enp3s0

INTERFACE
#########

5.1.5   Open interface 
  5.2.2   Interface ID:      docker0
          Interface Type:    GEV
          Interface Name:    docker0
5.1.13   Close interface (0 cameras found) 

5.1.5   Open interface 
  5.2.2   Interface ID:      enp2s0f0
          Interface Type:    GEV
          Interface Name:    enp2s0f0
   
        Opened interface - NodeList Information 
          GevInterfaceSubnetIPAddress: 192.168.2.101
          GevInterfaceSubnetMask:      255.255.255.0
  
DEVICE LIST
###########

5.1.6   Detected devices:         1
  5.2.3   Device DeviceID:        devicemodul3c_ef_8c_94_ba_a4
          Device Model:           A5501MG20
          Device SerialNumber:    2F01F38YAK00044
          Device Vendor:          Machine Vision
          Device TLType:          GEV
          Device AccessStatus:    RW
          Device UserID:          Camera0

DEVICE
######

5.1.7   Open first device 
          Device DeviceID:        devicemodul3c_ef_8c_94_ba_a4
          Device Model:           A5501MG20
          Device SerialNumber:    2F01F38YAK00044
          Device Vendor:          Machine Vision
          Device TLType:          GEV
          Device AccessStatus:    RW
          Device UserID:          Camera0

        Opened device - RemoteNodeList Information 
          Device AccessStatus:    RW
          DeviceSerialNumber:     2F01F38YAK00044
          DeviceManufacturerInfo: Machine Vision
          DeviceFirmwareVersion:  20170718,211828,00800000,2
          GevCCP:                 ControlAccess
          GevCurrentIPAddress:    0xc0a80205
          GevCurrentSubnetMask:   0xffffff00
  
DEVICE PARAMETER SETUP
######################

         TriggerMode:             Off

DATA STREAM LIST
################

5.1.8   Detected datastreams:     1
  5.2.4   DataStream ID:          Stream0

DATA STREAM
###########

5.1.9   Open first datastream 
          DataStream ID:          Stream0

        Opened datastream - NodeList Information 
          StreamAnnounceBufferMinimum:  1
          StreamDriverModel:            Socket
  
BUFFER LIST
###########

5.1.10   Announced buffers:       4 using 21233664 [bytes]
5.1.11   Queued buffers:          4
 
CAMERA START
############

5.1.12   DataStream started 
5.1.12   A5501MG20 started 
 
CAPTURE 12 IMAGES BY IMAGE POLLING
##################################

 Image     1 received in memory address 0x7f101aaed010
 Image     2 received in memory address 0x7f101aaed010
 Image     3 received in memory address 0x7f101aaed010
 Image     4 received in memory address 0x7f101aaed010
 Image     5 received in memory address 0x7f101aaed010
 Image     6 received in memory address 0x7f101aaed010
 Image     7 received in memory address 0x7f101aaed010
 Image     8 received in memory address 0x7f101aaed010
 Image     9 received in memory address 0x7f101aaed010
 Image    10 received in memory address 0x7f101aaed010
 Image    11 received in memory address 0x7f101aaed010
 Image    12 received in memory address 0x7f101aaed010
 
CAMERA STOP
###########

5.1.12   A5501MG20 stopped 

         ExposureTime:                   5000 [us]
         GevSCPSPacketSize:              9000 [bytes]
         GevSCPD (PacketDelay):          0 [tics]

         DataStream Statistics 
           DataBlockComplete:              12
           DataBlockInComplete:            0
           DataBlockMissing:               0
           PacketResendRequestSingle:      0
           PacketResendRequestRange:       0
           PacketResendReceive:            0
           DataBlockDroppedBufferUnderrun: 0
           Bitrate:                        860
           Throughput:                     20

         BufferList Information 
           DeliveredCount:        12
           UnderrunCount:         0

5.1.12   DataStream stopped 

RELEASE
#######

5.1.13   Releasing the resources 
         buffers after revoke:    0

End

Input any number to close the program:

**Comment by heikohimu** [comment]
It looks like AcquisitionStart is not ready (i.e. writable) at the time when gc_stream uses it. I also do not understand why AcquisitionStart is marked as NA in the output of gc_info. I can only guess ...

Can you replace CONTROL in tools/gc_stream.cc by EXCLUSIVE and recompile gc_stream. Does it make a difference?

Another possibility would be to add a sleep in front of the AqcuisitionStart command in rc_genicam_api/stream.cc. Maybe the camera needs some time before acquisition can be started.

**Comment by dmccskylove** [comment]
I've tested both of the methods you mentioned above. The same result.
I also tested another camera, basler's acA2500-14gm, with the same results.
The question that I can't understand is that I can capture images correctly in the Baumer example. Why can't almost the same operation be implemented?
![image](https://user-images.githubusercontent.com/6083168/49924110-55ce7500-fef0-11e8-88f6-742961efe690.png)
![image](https://user-images.githubusercontent.com/6083168/49924127-61ba3700-fef0-11e8-9c0b-504e6dae9538.png)

**Comment by dmccskylove** [comment]
Another information，I try to get AccessStatus after called open. "NoAccess" returned.
Are these two related?
![image](https://user-images.githubusercontent.com/6083168/49924600-c0cc7b80-fef1-11e8-8e02-72bac88d2cfd.png)

**Comment by heikohimu** [comment]
This is strange, because the gc_info output that you posted shows that the AccessStatus is ReadWrite. A difference is that gc_info prints the status without opening the device, while are requesting it after opening it. In any case, GenTL specifies that this information should be consistent. Thus, it should not matter if the device is open or not.

Actually, according to GenTL specification, "NoAccess" means "The device is seen by the producer but is not available for access because it is not reachable". Thus, it might be a networking problem. I can see in the gc_info output that a persistent IP was defined. Is the IP and subnet mask correct? On the other hand, if it works on the same computer with the Baumer software, then it should not be a networking problem.

Are you working under Windows? If yes, the Windows firewall might interfere. Can you switch it off, just for testing?

**Comment by heikohimu** [comment]
Have you checked network setup and firewall? Did it solve the issue?

**Comment by dmccskylove** [comment]
I am currently working in Ubuntu 16.04 environment. My understanding is that since the same configuration can work properly with other tools, it should be independent of the system environment.
Ultimately, I used baumer's lib to solve the problem. Thank you for your valuable time.

**Comment by heikohimu** [comment]
Yes, it should be independent. Its just that the Windows firewall likes to interfere, but this is not the problem here.

**Comment by wbt729** [comment]
I had the same issue as @dmccskylove using a Basler camera aCA 1300. What helped was to set `TLParamsLocked=1`. After this the `AcquisitionStart` truned from NA to RO:

`
    GenApi::IInteger* lock=dynamic_cast<GenApi::IInteger*>(parent->getRemoteNodeMap()->_GetNode("TLParamsLocked"));

    lock->FromString("1");

    GenApi::CCommandPtr start=parent->getRemoteNodeMap()->_GetNode("AcquisitionStart");
    start->Execute();`

**Comment by heikohimu** [comment]
This is an interesting information. We do not use TLParamsLocked in our sensor, but it I guess it would not harm to implement it. I will do that.

**Comment by luel1992** [comment]
I had a similiar issue and google search brought me here - I tried to get access to the Jumbo Frames (camera.GevSCPSPacketSize.SetValue(9000) ) but got the error
-->
_genicam.AccessException: Node is not writable. : AccessException thrown in node 'GevSCPSPacketSize' while calling 'GevSCPSPacketSize.SetValue()' (file 'integert.h', line 77)

with calling " camera.TLParamsLocked.SetValue(0) " before,     (0! not 1) , I had no issues anymore and could modify the jumbo frames. 

Access via python (pypylon) on a acA640-120gm

Maybe it will help other in the future
